rbenv installation as an unprivileged user

diff --git a/script/install-rbenv b/script/install-rbenv
--- a/script/install-rbenv
+++ b/script/install-rbenv
@@ -14,4 +14,14 @@ else
   git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
 fi
 
-sudo apt-get install gcc libssl-dev libreadline-dev zlib1g-dev
+packages="gcc libssl-dev libreadline-dev zlib1g-dev"
+missing=
+for package in $packages; do
+  if ! dpkg -s "$package" >/dev/null; then
+    echo "Missing package: $package"
+    missing="$missing $package"
+  fi
+done
+if test -n "$missing"; then
+  sudo apt-get install $missing
+fi
