br-sandbox setup

diff --git a/script/setup-br-sandbox b/script/setup-br-sandbox
--- a/script/setup-br-sandbox
+++ b/script/setup-br-sandbox
@@ -4,9 +4,20 @@ set -e
 
 . /etc/setup.conf
 
-if id me; then
+if test -z "$main_user"; then
+  if id me >/dev/null 2>/dev/null && ! id w >/dev/null 2>/dev/null; then
+    main_user=me
+  elif id w >/dev/null 2>/dev/null && ! id me >/dev/null 2>&1; then
+    main_user=w
+  else
+    echo 'Cannot determine main user' 1>&2
+    exit 1
+  fi
+fi
+
+if test "$main_user" = me; then
   `dirname "$0"`/setup-br-sandbox-me
-elif id w && test "$main_user" = w; then
+elif test "$main_user" = w; then
   exec `dirname "$0"`/setup-br sandbox 2523 w
 else
   echo 'Not handled' 1>&2
