check for xfs tools

diff --git a/script/setup-br b/script/setup-br
--- a/script/setup-br
+++ b/script/setup-br
@@ -46,7 +46,10 @@ fi
 
 if test -n "$zram_size" && ! df /mnt/browsers |tail +2 |awk '{print $1}' |fgrep -q zram; then
   modprobe zram
-  which mkfs.xfs
+  if ! which mkfs.xfs; then
+    echo "mkfs.xfs not in PATH, aborting" 1>&2
+    exit 1
+  fi
 
   num=`cat /sys/class/zram-control/hot_add`
   dev=/dev/zram$num
